# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"console": "00_cli_colors.ipynb",
         "create_docker_search_table": "00_cli_colors.ipynb",
         "docker_search": "00_cli_colors.ipynb",
         "create_docker_ls_table": "00_cli_colors.ipynb",
         "docker_container_ls": "00_cli_colors.ipynb",
         "inspect_container": "01_docker.ipynb"}

modules = ["cli_colors.py",
           "docker_startup.py"]

doc_url = "https://muellerzr.github.io/docker_buddy/"

git_url = "https://github.com/muellerzr/docker_buddy/tree/master/"

def custom_doc_links(name): return None
